### ISSUE TITLE
Creative Reaction Lab Diversity Training

### ISSUE THREAD

**Issue by quarterback** [18F/product-design#23]
for just design chapter

**Comment by cmajel** [comment]
Keeping this up to date...

* We had interest from 52 folks across TTS, so a mix of 18F and other groups, as well as multiple disciplines.
* We've confirmed a price and time with the training provider: Aug 5 at 1:30 - 3:30PM ET / 12:30-2:30PM CT
* Anne  to identify who signs the final approval 🤞 

Hoping for a positive update very soon.
